export const surpriseMePrompts = [
  "a beatiful sunset with mountains in the background and a lake with glacier water in the foreground",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "Photo of cyberpunk face",
  "Ghostly Pirate Ship",
  "Eclipse",
  "Purple Purring Princess",
  "overgrown and destroyed building",
  "A sloth playing a guitar, photograph 35mm lens",
  "A pizza eating hamster on a Hawaiian beach",
  "A man who is taking a photograph with his digital camera",
  "a cabin surrounded by fog, red lights shining out of windows. cornfield",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "Photo of pond with lotus flower",
  "A plush toy robot sitting against a yellow wall",
  "A Baby Fennec Sneezing Onto A Strawberry, Detailed, Macro, Studio Light, Droplets, Backlit Ears",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A Cup Of Coffee On A Saucer With A Spoon, A Tilt Shift Photo, Anamorphic Bokeh, Italian",
  "A centered explosion of colorful powder on a black background",
  "minimalism arch gate view to the sea beach living santorini island style",
  "A photo of a white fur monster standing in a purple room",
  "Portrait Of A Fashionable Black Man, 80S Fashion, Colorful Studio Lighting,",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "Photo of silhouette of person using their phone outside",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A futuristic cyborg dance club, neon lights",
  "Photo of rose red boom",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "Photo of 1970s sun cult",
  "Photo of artificial intelligence that is an accomplished writer",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "Photo of triangle bird shapes that fly in formation",
  "Photo of lost in an alley on a friday night",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "Photo Of Abstract Green Fields Ble Sky Watrfall Water",
  "Rocket-launched photo space",
];
